### ISSUE TITLE
Just use Cpanel::JSON::XS::Type...

### ISSUE THREAD

**Issue by Grinnz** [kfly8/p5-JSON-TypeEncoder#1]
I appreciate what you were trying to do, but there are a number of problems with this module - it does no escaping of input, so many types of input will produce invalid or wrong JSON; it reinvents the encoding of JSON in pureperl without learning from any of the mistakes of JSON::PP and Mojo::JSON over the years (I suggest looking at the source of Mojo::JSON to see it correctly done); it does not encode to UTF-8 or document that JSON must be encoded to UTF-8 before output, thus replicating the years of people tripped up by to_json; and JSON has a specific set of types which are not really relevant to Type::Tiny types for Perl values. Cpanel::JSON::XS::Type already solves this without any of these problems.

**Comment by kfly8** [comment]
Thank you very much for telling me.
I'll think about it.

**Comment by kfly8** [comment]
As a result of thinking, I thought you were right. So, I will do the following things.

- Removed from CPAN
- Escape input, modify document

Thank you for telling me.
